# Generated by Django 5.1 on 2024-08-15 11:32

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(default='en', max_length=5, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('locale', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.IntegerField(null=True)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('url', models.URLField(max_length=255)),
                ('error_message', models.TextField()),
                ('stack_trace', models.TextField(blank=True, null=True)),
                ('additional_data', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('date_of_birth', models.DateField(default='2000-01-01')),
                ('final_age', models.IntegerField(choices=[(27, '27'), (50, '50'), (60, '60'), (70, '70'), (80, '80'), (90, '90'), (100, '100'), (120, '120')], default=80)),
                ('premium_date', models.DateField(default=datetime.datetime(2024, 8, 22, 11, 32, 55, 219613, tzinfo=datetime.timezone.utc))),
                ('sorting_descending', models.BooleanField(default=True)),
                ('sorting_type', models.CharField(choices=[('days', 'Days'), ('full', 'Full'), ('topics', 'Topics')], default='days', max_length=10)),
                ('reminder_day', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], default=1)),
                ('session_minutes', models.IntegerField(default=30)),
                ('mailing', models.BooleanField(default=True)),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.language')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('summary', models.TextField(blank=True, max_length=5000)),
                ('active', models.BooleanField(default=True)),
                ('ordering', models.IntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Topics',
            },
        ),
        migrations.CreateModel(
            name='Original_Note',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(max_length=500)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.week')),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('sender', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField(max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.topic')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.week')),
            ],
        ),
        migrations.CreateModel(
            name='Weeki',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('favorite', models.BooleanField(default=False)),
                ('content', models.TextField(max_length=500)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.topic')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.week')),
            ],
        ),
        migrations.AddField(
            model_name='week',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.year'),
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.TextField()),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='app.language')),
            ],
            options={
                'indexes': [models.Index(fields=['key', 'language'], name='app_transla_key_dc1eb4_idx')],
                'unique_together': {('key', 'language')},
            },
        ),
    ]
