# Generated by Django 5.1 on 2024-08-15 11:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='premium_date',
            field=models.DateField(default=datetime.datetime(2024, 8, 22, 11, 33, 38, 898216, tzinfo=datetime.timezone.utc)),
        ),
    ]
