# Generated by Django 5.0.2 on 2024-07-13 07:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_profile_theme_weeki_image_alter_week_value_vision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('short', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='weeki',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='category',
            name='color_1',
        ),
        migrations.RemoveField(
            model_name='category',
            name='color_2',
        ),
        migrations.RemoveField(
            model_name='category',
            name='color_3',
        ),
        migrations.RemoveField(
            model_name='weeki',
            name='intensity',
        ),
        migrations.AddField(
            model_name='weeki',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('url', models.URLField(max_length=255)),
                ('error_message', models.TextField()),
                ('stack_trace', models.TextField(blank=True, null=True)),
                ('additional_data', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.language'),
        ),
    ]
