# Generated by Django 5.1 on 2024-08-16 13:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_profile_premium_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='created_at',
        ),
        migrations.AddField(
            model_name='topic',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='premium_date',
            field=models.DateField(default=datetime.datetime(2024, 8, 23, 13, 9, 38, 495702, tzinfo=datetime.timezone.utc)),
        ),
    ]
