# Generated by Django 5.0.2 on 2024-07-13 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_language_rename_user_id_weeki_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='year_of_death',
            new_name='final_age',
        ),
    ]
