# Generated by Django 5.0.2 on 2024-07-28 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_year_of_death_profile_final_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='short',
            new_name='locale',
        ),
        migrations.AddField(
            model_name='language',
            name='code',
            field=models.CharField(default='en', max_length=5, unique=True),
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.TextField()),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='app.language')),
            ],
            options={
                'indexes': [models.Index(fields=['key', 'language'], name='app_transla_key_dc1eb4_idx')],
                'unique_together': {('key', 'language')},
            },
        ),
    ]
