# Generated by Django 5.1 on 2024-08-20 15:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_profile_reminder_hour_alter_profile_premium_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='premium_start',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 8, 20, 15, 5, 12, 960226, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='premium_date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 8, 27, 15, 5, 12, 960194, tzinfo=datetime.timezone.utc)),
        ),
    ]
