# Generated by Django 5.0.2 on 2024-08-05 21:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_profile_theme_remove_vision_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='premium_date',
            field=models.DateField(default=datetime.datetime(2024, 8, 12, 21, 0, 11, 315086, tzinfo=datetime.timezone.utc)),
        ),
    ]
