# Generated by Django 5.1 on 2024-08-24 11:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_aimodel_prompt_temperature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='max_tokens',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='premium_date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 8, 31, 11, 45, 50, 794435, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='premium_start',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 8, 24, 11, 45, 50, 794455, tzinfo=datetime.timezone.utc)),
        ),
    ]
