# Generated by Django 5.1 on 2024-08-24 15:13

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_profile_premium_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prompt_debug',
            name='user',
        ),
        migrations.AlterField(
            model_name='profile',
            name='premium_date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 8, 31, 15, 13, 19, 918622, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='premium_start',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 8, 24, 15, 13, 19, 918641, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='prompt_debug',
            name='prompt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.prompt'),
        ),
    ]
