# Generated by Django 5.1 on 2024-08-28 14:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_profile_premium_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='week',
        ),
        migrations.AlterField(
            model_name='profile',
            name='premium_date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 9, 4, 14, 44, 15, 827630, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='premium_start',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 8, 28, 14, 44, 15, 827661, tzinfo=datetime.timezone.utc)),
        ),
    ]
