# Generated by Django 5.1 on 2024-08-28 16:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_conversation_topic_remove_conversation_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='session',
            new_name='conversation_session',
        ),
        migrations.AlterField(
            model_name='profile',
            name='premium_date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 9, 4, 16, 7, 43, 210261, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='premium_start',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 8, 28, 16, 7, 43, 210281, tzinfo=datetime.timezone.utc)),
        ),
    ]
