# Generated by Django 5.1 on 2024-08-31 13:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_profile_topic_view_alter_profile_premium_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation_session',
            old_name='created_at',
            new_name='date_created',
        ),
        migrations.AlterField(
            model_name='profile',
            name='premium_date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 9, 7, 13, 33, 23, 583893, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='premium_start',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 8, 31, 13, 33, 23, 583949, tzinfo=datetime.timezone.utc)),
        ),
    ]
