# Generated by Django 5.1 on 2024-09-05 14:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_profile_language_alter_profile_premium_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='premium_date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 9, 19, 14, 52, 32, 786065, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='premium_start',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 9, 5, 14, 52, 32, 786086, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sorting_type',
            field=models.CharField(choices=[('days', 'Days'), ('full', 'Full'), ('topics', 'Topics')], default='topics', max_length=10),
        ),
    ]
