# Generated by Django 5.1 on 2024-09-06 19:55

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_profile_premium_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='session_minutes',
        ),
        migrations.AddField(
            model_name='profile',
            name='chats_available',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='premium_date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 9, 20, 19, 55, 16, 286604, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='premium_start',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 9, 6, 19, 55, 16, 286626, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='topic_view',
            field=models.CharField(choices=[('weekis', 'Weekis'), ('chats', 'Chats'), ('sums', 'Sums')], default='weekis', max_length=13),
        ),
        migrations.AlterField(
            model_name='topic',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.CreateModel(
            name='Sums',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True, max_length=500)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.topic')),
                ('week_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.week')),
            ],
        ),
    ]
