# Generated by Django 5.1 on 2024-09-06 20:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_profile_premium_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sum',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='sum',
            old_name='week_id',
            new_name='week',
        ),
        migrations.AlterField(
            model_name='profile',
            name='premium_date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 9, 20, 20, 33, 45, 166167, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='premium_start',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 9, 6, 20, 33, 45, 166191, tzinfo=datetime.timezone.utc)),
        ),
    ]
