# Generated by Django 5.1 on 2024-09-09 14:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_rename_user_id_sum_user_rename_week_id_sum_week_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='chat_sessions_available',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='chats_available',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='premium_date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 9, 23, 14, 32, 33, 90897, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='premium_start',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 9, 9, 14, 32, 33, 90919, tzinfo=datetime.timezone.utc)),
        ),
    ]
