# Generated by Django 5.1 on 2024-09-13 16:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_alter_profile_premium_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_purpose', models.TextField(verbose_name='What do you think is the main purpose of the app?')),
                ('most_confusing', models.TextField(verbose_name='What was the most confusing for you in the app? Why was it confusing?')),
                ('favorite_feature', models.TextField(verbose_name='What feature did you enjoy the most? And why?')),
                ('missing_function', models.TextField(verbose_name='What function are you missing in this app?')),
                ('APP_USE_RATING', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('TAKING_NOTES_RATING', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('RECORDING_NOTES_RATING', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('CHAT_WITH_MR_WEEK_RATING', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('REGISTRATION_PROCESS_RATING', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('ADDING_WEEKI_NOTE_RATING', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('DASHBOARD_ORIENTATION_RATING', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('HOMEPAGE_RATING', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('LOGIN_PROCESS_RATING', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('MR_WEEK_CONVERSATIONS_RATING', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('ADDING_CATEGORIES_RATING', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('RECORDING_BUTTON_RATING', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('BIG_NOTE_ACROSS_TOPICS_RATING', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('WEEKLY_NOTES_SUMMARY_RATING', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('DASHBOARD_PICTURE_GENERATION_RATING', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('user_comment', models.TextField(blank=True, verbose_name='Any additional comments?')),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='premium_date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 9, 27, 16, 30, 21, 969793, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='premium_start',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 9, 13, 16, 30, 21, 969827, tzinfo=datetime.timezone.utc)),
        ),
    ]
