# Generated by Django 5.1 on 2024-10-02 19:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_appfeedback_alter_profile_premium_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Conversation',
            new_name='Message',
        ),
        migrations.AlterField(
            model_name='profile',
            name='premium_date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 10, 16, 19, 12, 3, 881626, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='premium_start',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 10, 2, 19, 12, 3, 881645, tzinfo=datetime.timezone.utc)),
        ),
    ]
