# Generated by Django 5.1 on 2024-10-02 19:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_rename_conversation_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='premium_date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 10, 16, 19, 34, 35, 948006, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='premium_start',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 10, 2, 19, 34, 35, 948025, tzinfo=datetime.timezone.utc)),
        ),
    ]
