# Generated by Django 5.1 on 2024-12-09 16:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_profile_image_alter_profile_premium_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat_session',
            name='day',
        ),
        migrations.RemoveField(
            model_name='chat_session',
            name='month',
        ),
        migrations.RemoveField(
            model_name='chat_session',
            name='year',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='chat_sessions_available',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='chats_available',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='premium_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='premium_start',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='sorting_type',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='topic_view',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='day',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='month',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='year',
        ),
        migrations.AddField(
            model_name='chat_session',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='chat_session',
            name='date_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='profile',
            name='reminder',
            field=models.BooleanField(choices=[(True, 'True'), (False, 'False')], default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='tokens',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='summary',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
