# Generated by Django 5.1.4 on 2024-12-11 14:03

import app.models
import django.utils.timezone
import functools
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_remove_chat_session_day_remove_chat_session_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat_session',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='chat_session',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=functools.partial(app.models.get_upload_path, *('chat',), **{})),
        ),
    ]
