# Generated by Django 5.1.4 on 2024-12-11 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_chat_session_date_chat_session_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat_session',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='chat_session',
            name='date_updated',
        ),
        migrations.AddField(
            model_name='chat_session',
            name='time_left',
            field=models.IntegerField(default=60),
        ),
    ]
