# Generated by Django 5.1.4 on 2024-12-12 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_remove_chat_session_date_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat_session',
            name='date',
        ),
    ]
