# Generated by Django 5.1.4 on 2024-12-12 08:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_remove_chat_session_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat_session',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
