# Generated by Django 5.1.4 on 2024-12-12 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_chat_session_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subscription_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
