# Generated by Django 5.1.4 on 2024-12-16 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_remove_chat_session_image_remove_profile_bio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='summary',
            old_name='date_created',
            new_name='date',
        ),
    ]
