# Generated by Django 5.1.4 on 2024-12-24 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_remove_profile_final_age_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat_session',
            name='first',
            field=models.BooleanField(default=False),
        ),
    ]
