# Generated by Django 5.1.4 on 2024-12-31 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_chat_session_summary_profile_character_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='date_updated',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
