# Generated by Django 5.1.4 on 2025-01-02 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_pastcharacters_pasttopics'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat_session',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
