# Generated by Django 5.1.4 on 2025-01-03 14:14

import app.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_chat_session_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EncryptedUserFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', app.models.EncryptedCharField(blank=True, max_length=150)),
                ('last_name', app.models.EncryptedCharField(blank=True, max_length=150)),
                ('email', app.models.EncryptedEmailField(max_length=254)),
                ('username', app.models.EncryptedCharField(max_length=150)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
