# Generated by Django 5.1.4 on 2025-02-11 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_chat_session_reminder_sent_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat_session',
            name='chars_since_check',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topic',
            name='confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='topic',
            name='currrent_session_status',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Cache'), (2, 'Current')], default=0),
        ),
    ]
