# Generated by Django 5.1.4 on 2025-02-19 11:39

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_chat_session_chars_since_check_topic_confidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat_session',
            name='potential_topic',
            field=app.models.EncryptedTextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='chat_session',
            name='saved_query',
            field=app.models.EncryptedTextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='currrent_session_status',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Cache')], default=0),
        ),
    ]
