# Generated by Django 5.1.4 on 2025-02-25 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0057_chat_session_potential_topic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='currrent_session_status',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Cache'), (2, 'Current')], default=0),
        ),
    ]
