# Generated by Django 5.1.4 on 2025-03-10 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0058_profile_last_login_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='currrent_session_status',
        ),
        migrations.CreateModel(
            name='SessionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'No'), (1, 'Cache'), (2, 'Current')], default=0)),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_logs', to='app.log')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_logs', to='app.chat_session')),
            ],
        ),
        migrations.AddField(
            model_name='chat_session',
            name='logs',
            field=models.ManyToManyField(related_name='sessions', through='app.SessionLog', to='app.log'),
        ),
        migrations.CreateModel(
            name='SessionTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'No'), (1, 'Cache'), (2, 'Current')], default=0)),
                ('confidence', models.FloatField(default=0.0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_topics', to='app.chat_session')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_topics', to='app.topic')),
            ],
        ),
        migrations.AddField(
            model_name='chat_session',
            name='topics',
            field=models.ManyToManyField(related_name='sessions', through='app.SessionTopic', to='app.topic'),
        ),
        migrations.AddIndex(
            model_name='sessionlog',
            index=models.Index(fields=['session', 'status'], name='app_session_session_491093_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionlog',
            index=models.Index(fields=['log', 'status'], name='app_session_log_id_85f2fb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sessionlog',
            unique_together={('session', 'log')},
        ),
        migrations.AddIndex(
            model_name='sessiontopic',
            index=models.Index(fields=['session', 'status'], name='app_session_session_87b261_idx'),
        ),
        migrations.AddIndex(
            model_name='sessiontopic',
            index=models.Index(fields=['topic', 'status'], name='app_session_topic_i_b9169a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sessiontopic',
            unique_together={('session', 'topic')},
        ),
    ]
