# Generated by Django 5.1.4 on 2025-03-14 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0059_remove_topic_currrent_session_status_sessionlog_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='confidence',
        ),
    ]
