# Generated by Django 5.1.4 on 2025-05-12 10:44

import app.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0061_remove_chat_session_chars_since_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat_session',
            name='character',
            field=app.models.EncryptedTextField(blank=True, max_length=2000, null=True),
        ),
    ]
