# Generated by Django 5.1.4 on 2025-05-12 12:39

import app.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0062_chat_session_character'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat_session',
            name='asked_questions',
            field=app.models.EncryptedTextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='chat_session',
            name='potential_topic',
            field=app.models.EncryptedTextField(blank=True, max_length=5000, null=True),
        ),
    ]
