# Generated by Django 5.1.4 on 2025-05-17 14:27

import app.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0064_chat_session_topic_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat_session',
            name='topic_ids',
            field=app.models.EncryptedTextField(blank=True, max_length=1000, null=True),
        ),
    ]
