# Generated by Django 5.1.4 on 2025-05-20 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0065_chat_session_topic_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='show_in',
            field=models.BooleanField(default=True),
        ),
    ]
