# Generated by Django 5.0.2 on 2024-05-05 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='BlogPost',
        ),
    ]
