# Generated by Django 5.0.2 on 2024-05-13 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blogpost_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='thumb',
            field=models.ImageField(blank=True, default='default.png', upload_to='blog_images'),
        ),
    ]
